import fs from "node:fs";
import path from "node:path";
const dir=path.resolve("data/legacy");
const core=fs.readdirSync(dir).filter(n=>/^hotels-core-\d+\.json$/.test(n)).sort().flatMap(n=>JSON.parse(fs.readFileSync(path.join(dir,n),"utf8")));
const content=fs.readdirSync(dir).filter(n=>/^hotel-content-\d+\.sanitized\.json$/.test(n)).sort().flatMap(n=>JSON.parse(fs.readFileSync(path.join(dir,n),"utf8")));
const byId=new Map(content.map(r=>[r.id,r]));
const titles=core.map(r=>r.name+": price, value & traveler evidence | SecretNests");
const descs=core.map(r=>String(byId.get(r.id)?.description||"").trim());
const duplicateDescriptions=[...descs.reduce((m,d)=>{if(d)m.set(d,(m.get(d)||0)+1);return m},new Map())].filter(([,n])=>n>1);
const report={hotels:core.length,duplicate_titles:titles.length-new Set(titles).size,duplicate_descriptions:duplicateDescriptions.length,thin_descriptions:descs.filter(d=>d.length<80).length,overly_long_titles:titles.filter(t=>t.length>70).length,overly_long_descriptions:descs.filter(d=>d.length>320).length,missing_country:core.filter(r=>!r.country).length};
fs.mkdirSync(".generated",{recursive:true}); fs.writeFileSync(".generated/seo-qa.json",JSON.stringify(report,null,2)); console.log(JSON.stringify(report,null,2));
if(report.hotels!==1066||report.duplicate_titles||report.duplicate_descriptions||report.thin_descriptions) process.exitCode=1;